steps:
- name: gradle:7.4.2-jdk17
  entrypoint: gradle
  args: [ 'assemble' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'myapp', '--image', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated' ]
